# Mistral RAG System

A lightweight **Retrieval-Augmented Generation (RAG)** system built using **FastAPI, ChromaDB, LangChain, Mistral AI, and Streamlit**.

This project allows users to upload documents, store their embeddings in a local vector database, and ask natural-language questions that are answered using retrieved context from those documents.

---

## ✨ Features

- Upload documents: **PDF, DOCX**
- Optional support for **PPTX and Images** (based on Python version & dependencies)
- Automatic text extraction and chunking
- Embedding generation using **Mistral AI embeddings**
- Persistent vector storage using **ChromaDB**
- Semantic similarity search
- Context-aware answers generated by **Mistral LLM**
- REST API (FastAPI) + Interactive UI (Streamlit)

---

## 🧠 Architecture Overview

```text
User
 ├── Uploads Document
 │
 ├── FastAPI Backend
 │     ├── Text Extraction
 │     ├── Chunking
 │     ├── Embedding (Mistral)
 │     └── Storage (ChromaDB)
 │
 ├── Query
 │
 └── Retrieval + Answer Generation (Mistral LLM)
📁 Project Structure
text
Copy code
mistral-rag-system/
│
├── app.py              # Streamlit frontend
├── main.py             # FastAPI backend
├── utils.py            # RAG utilities (embedding, storage, retrieval)
├── requirements.txt    # Python dependencies
├── .env.example        # Environment variable template
├── uploads/            # Temporary uploaded files
└── chroma_db/          # Persistent ChromaDB storage


⚠️ Python Version Notes

Python 3.13

❌ Image & PPTX processing may not work

Python 3.12 or lower

✅ Full support for images and PowerPoint files

🧩 Tech Stack-

FastAPI — Backend API
Streamlit — Frontend UI
ChromaDB — Vector database
LangChain — RAG orchestration
Mistral AI — Embeddings + LLM

🚀 Quick Start
1️⃣ Install Dependencies
bash
Copy code
pip install -r requirements.txt
2️⃣ Configure Environment Variables
Create a .env file in the project root:

env
Copy code
MISTRAL_API_KEY=your_mistral_api_key_here
Get your API key from:
👉 https://console.mistral.ai

3️⃣ Run the Backend (FastAPI)
bash
Copy code
uvicorn main:app --reload
Backend will be available at:
👉 http://localhost:8000

4️⃣ Run the Frontend (Streamlit)
bash
Copy code
streamlit run app.py
UI will open at:
👉 http://localhost:8501
